version: 2.1
orbs:
  node: circleci/node@2.1.0

jobs:
  # test:
  #   executor:
  #     name: node/default
  #     tag: "12.16.2"
  #   steps:
  #     - checkout
  #     - node/install-packages
  #     - node/test

  deploy:
    executor:
      name: node/default
      tag: "12.16.2"
    parameters:
      stage:
        description: Stage to provision infrastructure for
        type: string
        default: ""
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Deploy infrastructure
          command: |
            STAGE=<< parameters.stage >>
            [[ ! -z "$STAGE" ]] || STAGE=${CIRCLE_BRANCH%%/*}
            echo Creating infrastructure for stage $STAGE
            npm run deploy -- --stage $STAGE

workflows:
  test-and-deploy:
    jobs:
      - node/test:
          version: "12.16.2"
      - deploy:
          requires: [node/test]
          context: aws-manwaring
          stage: automation
